### ISSUE TITLE
Enter for some shortcuts

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#12]
Hi there, I am curious if its possible to not need the ENTER_SYMBOL when starting navigator. You know how some of the first blocks are numbered with a number followed by ENTER_SYMBOL.

I see in flow it would be nice if you can just type a number and go.

Thanks

**Comment by mgsloan** [comment]
The reason for sometimes needing to press enter is that otherwise there are ambiguities.  For example, if there are 40 blocks, and you type `1`, are you intending to jump to the first block, or are you about to press `0` to jump to block 10?

It could probably have the enter symbol appear less often, currently it is based on the number of digits in the largest block number.  So you still have to press enter after `5` in this example, even though there is no block 50.

Open to alternative suggestions

**Comment by TfTHacker** [comment]
Ok, this makes sense. So obvious now that you explain it :-)
