### ISSUE TITLE
example of using let keysToIgnore =  {  }

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#2]
Hi, I am trying to use  let keysToIgnore =  {  }, but no matter what letters I feed in, they are not ignored. How is this variable to be used?

THanks, sorry for being  a pain.

**Comment by mgsloan** [comment]
Hey, this variable is being used to track some mutable state to avoid some
weird corner cases with keyboard interaction.  It is not a constant
intended to be set.  Below I'll explain what it is since I already typed
the explanation.

I assume that you want to allow certain shortcuts during navigation mode?
That should be feasible by adding an if statement in the keydown handler
which ignores particular key combinations.  One thing in particular that
could be done that would be rather generally, would be to not handle any
keypresses which have `ctrl` modifier or `alt` modifier (and are not
`alt-g`).  This is actually on my list of things to improve, it would
generally be a good enhancement, feel free to open a PR for it!

----

If I recall correctly, the reason for it is that the user might press a key
in navigation mode, which causes focus to switch to an input.  Then, the
keypress / keyup events for the event get sent to the input element.  The
keydown / keyup handlers roam-navigator installs selectively skips events
for keys where the keydown was initiated in navigation mode.

There may be a more elegant solution to this involving an invisible input
element that has focus in navigation mode, but hey this works.

**Comment by mgsloan** [comment]
Actually, I'm making the change now to skip modifier keys since I'm already
looking at the code and the change is relatively clear.

**Comment by mgsloan** [comment]
I've pushed a commit which now ignores keydown events that use `ctrl` or `alt`.  Does that resolve the issue?

**Comment by TfTHacker** [comment]
Mike,
Thank you for your quick response. I will test the code out here soon. Roam42 does have a lot of keystrokes, but I think they don't conflict with ALT-G. I was looking to merge the keys, but now I think it might be wiser to keep them separate.

Just curious, have you done cross platform testing? This is one of the things I find the most difficult. Alt-G for example wasn't working on my iPad, but iPad keyboard is really odd.

Your code basically works as is on drop down. I have few conflicts to resolve, but this code you have done is a real labor of love, lots of code here :-)

**Comment by mgsloan** [comment]
I haven't done cross platform testing, I only use linux on thinkpads :)
