### ISSUE TITLE
Close right sidebar blocks

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#6]
Mike,
A number of Roam42 users have asked about a shortcut to close blocks that are in the right sidebar (basically where ever an X shows up). I was going to add this to my shortcut keyboard list, but it seems like a natural fit for the navigator code. Have you thought about adding that?

Perhaps it could be like a c1, c2, c3 etc shorctut for each open block that has an x? 

I wanted to see if this was in your plans before proceeding?

**Comment by mgsloan** [comment]
Hey, sure I think this does belong in Roam Navigator.

I'm thinking of using `x` as the starting keys, since the close icon looks like an x already.  So, `x1`, `x2`, etc.  This is also nice because `x` is an uncommon letter to start a word, and so won't collide as much as other characters would with existing key assignments.

It might take me a week or two to get around to adding it.

**Comment by TfTHacker** [comment]
Mike, I agree. Seems like a natural fit and I like your concept of X

**Comment by mgsloan** [comment]
Added in version 10! (along with a bunch of other improvements)

**Comment by mgsloan** [comment]
Err, make that version 11
